In [1]:
import tensorflow as tf

/devkit/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


#### 一. 创建Variable
1. 使用'tf.get_variable()'声明 :  
  1. 指定参数名  
  2. 指定变量的shape
  3. 指定变量的初始化器. 若不是随机初始化, 则可以不必指定shape

In [6]:
init_var = tf.get_variable('init_variable',shape=[4,2,2],initializer=tf.zeros_initializer())
# 变量可重复
# tf.get_variable_scope().reuse_variables() 
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(init_var))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


#### 二. 将变量加入集合
1. tensorflow默认的2个集合 :  
  1. `tf.GraphKeys.GLOBAL_VARIABLES` : 多条机器共享该变量  
  2. `tf.GraphKeys.TRAINABLE_VARIABLES` : 这些变量将计算梯度  
  3. `tf.GraphKeys.LOCAL_VARIABLES` : 本地变量, 不计算梯度

In [14]:
# 2.增加集合
tf.add_to_collection('my_local_collection',init_var)
# 3.获取集合下面的所有变量
tf.get_collection('my_local_collection')

[<tf.Variable 'init_variable:0' shape=(4, 2, 2) dtype=float32_ref>]

#### 三. 使用Variable
1. 像`tf.Tensor`一样使用`tf.Variable`

In [ ]:
# with tf.variable_scope('conv',reuse=True):
v = tf.get_variable('v',shape=[5,2],initializer=tf.zeros_initializer())
w = v+1

In [ ]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(w))